### PR TITLE
fix: missing backer information and cross origin errors

### LINKED ISSUE #1465: BUG - Bounty payments not displayed (for successful payments)
### ISSUE

**Bounty details are not displayed on issue page:s**.
* Bounty payments
* Bounty amounts
* Backer details

**Payment is successful:**
The payment has been debited from backers Paypal account.
The admin page for the issue has registered as funded

Eg. https://www.bountysource.com/issues/59613396-choose-alternative-download-location-in-settings-external-sd

image

Console logs screenshot might be a red-herring.
Recent PR https://github.com/bountysource/core/pull/1463 addressed some other Paypal issues where bounties were debited but not registered at all.  

These may be related.

### REQUIRED

Identify how the Issue page can fail to display details that are available to the admin page of the same issue?

### PR DESCRIPTION
**Pull request by brymut**
Resolves #1465 

### Description
Fixed a couple of errors:
- Empty backers list in issue/bounty page due to `bounty_refunded` failing query
- Cross-origin errors caused by failing API calls due to some routing errors and a querying error.

**Changes made**
- Change made in #1454 broke the bounty not_refunded query. Affecting the backer's list in the issue/bounty page, switched to `OR`.
- Removed `.pluck` method call as the switch to `find_by` in #1442 returns the model instance (instead of a collection like previously) which does not have the method. Refer to `person_id` field directly.
- Disabled 'autotrack' to stop Mixpanel client lib from calling `decide` API route.
- Changed 'track' API route for Mixpanel to accept appropriate POST method instead of GET which doesn't accept the send form data.

### CODE REVIEW

File: app/models/bounty.rb [hunk 1]
```diff
@@ -65,12 +65,11 @@ def self.all
   scope :active, lambda { where(status: Status::ACTIVE) }
   scope :refunded, lambda { where(status: Status::REFUNDED) }
   scope :paid, lambda { where(status: Status::PAID) }
-  scope :not_refunded, lambda { where("status < :status AND status > :status", status: Status::REFUNDED) }
-
+  scope :not_refunded, lambda { where("status != :status", status: Status::REFUNDED) }
```
Comment (alphashuro) [inline app/models/bounty.rb:68]: What is the reasoning behind this change?

File: app/controllers/track_controller.rb [hunk 2]
```diff
@@ -18,4 +18,22 @@ def track
...
+
+    headers['Access-Control-Allow-Methods'] = 'GET, POST, PATCH, PUT, DELETE'
+    headers['Access-Control-Allow-Headers'] = 'Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, X-Requested-With'
+    headers['Access-Control-Max-Age'] = '86400'
+    headers['Cache-Control'] = "no-cache, no-store, max-age=0, must-revalidate"
+    headers['Pragma'] = "no-cache"
+    headers['Expires'] = "Fri, 01 Jan 1990 00:00:00 GMT"
+    head :ok
+  end
+
```
Comment (alphashuro) [inline app/controllers/track_controller.rb:38]: This seems more like monkey patching, what do you think about looking for a way to prevent the lib from calling this endpoint to begin with if it's not being used?

File: app/models/bounty.rb (hunk 1 above)
Comment (brymut) [reply app/models/bounty.rb:68]: I just reverted it, the previous change broke the query.

File: app/controllers/track_controller.rb (hunk 2 above)
Comment (brymut) [reply app/controllers/track_controller.rb:38]: That was my first approach, to find the part of the client lib calling the endpoint based on the docs, but I couldn't find anything and I also didn't want to inadvertently disable any feature bounty source is currently using that I'm not aware of. I'll go through the docs again and see if I can come up with something else.

Comment (brymut) [reply app/controllers/track_controller.rb:38]: Okay, I seem to have found something. Based on the docs [here](https://developer.mixpanel.com/docs/javascript-full-api-reference#mixpanelinit) 'autotrack' is a Mixpanel object config option that enables autotracking on your website[ without any additional implementation.](https://mixpanel.com/de/autotrack/)  A feature that seems like bountysource wasn't using, and it seems like the feature is also being [retired](https://help.mixpanel.com/hc/en-us/articles/115004600343-Autotrack-Retirement) anyway.

 So I have set the `autotrack` config option to false, and the library has stopped calling that endpoint. I browsed bountysource some more locally using a test user and it seems like the current tracking implementation is still working, as the track endpoint is still being called and events are still being logged into the `mixpanel_events` table (mp_page_view, Create Order, etc)

File: app/models/bounty.rb (hunk 1 above)
Comment (alphashuro) [reply app/models/bounty.rb:68]: The fix for this actually needs to be `status < :status OR status > :status`

Comment (brymut) [reply app/models/bounty.rb:68]: Have you tested this?

**Comment by brymut** [comment]
Hi @alphashuro, I think that should be it now. Could you please have another quick look?
